Repository windsorcli/cli, pull requests merged in 2024-12, with the labels that each got.

#199 Add TF_VAR_os_type env var
  internal/env/shims.go
  internal/env/shims_test.go
  internal/env/terraform_env.go
  internal/env/terraform_env_test.go
Labels: chore

#210 Enhanced exec methods
  cmd/exec.go
  cmd/exec_test.go
  go.mod
  go.sum
  internal/network/colima_network.go
  internal/network/colima_network_test.go
  internal/network/darwin_network.go
  internal/network/darwin_network_test.go
  internal/network/linux_network.go
  internal/network/linux_network_test.go
  internal/network/network_test.go
  internal/network/windows_network.go
  internal/network/windows_network_test.go
  internal/services/localstack_service_test.go
  internal/shell/mock_shell.go
  internal/shell/mock_shell_test.go
  internal/shell/secure_shell.go
  internal/shell/secure_shell_test.go
  internal/shell/shell.go
  internal/shell/shell_test.go
  internal/shell/shims.go
  internal/stack/windsor_stack.go
  internal/stack/windsor_stack_test.go
  internal/virt/colima_virt.go
  internal/virt/colima_virt_test.go
  internal/virt/docker_virt.go
  internal/virt/docker_virt_test.go
Labels: enhancement

#211 Extend config to include node info
  internal/config/config.go
  internal/config/defaults.go
  internal/services/talos_controlplane_service.go
  internal/services/talos_controlplane_service_test.go
  internal/services/talos_worker_service.go
  internal/services/talos_worker_service_test.go
  internal/virt/docker_virt.go
Labels: chore

#214 Blueprint jsonnet
  blueprint.jsonnet
  go.mod
  go.sum
  internal/blueprint/blueprint_handler.go
  internal/blueprint/blueprint_handler_test.go
  internal/blueprint/blueprint_v1alpha1.go
  internal/blueprint/shims.go
  internal/generators/shims.go
  internal/generators/terraform_generator.go
  internal/generators/terraform_generator_test.go
  internal/services/talos_controlplane_service.go
  internal/services/talos_controlplane_service_test.go
  internal/services/talos_worker_service.go
  internal/services/talos_worker_service_test.go
  internal/stack/stack_test.go
  internal/stack/windsor_stack.go
  internal/stack/windsor_stack_test.go
Labels: feature

#215 Default local blueprint
  cmd/init.go
  internal/blueprint/blueprint_handler.go
  internal/blueprint/blueprint_handler_test.go
  internal/blueprint/templates/local.jsonnet
Labels: feature

#216 Version command fix
  .github/workflows/ci.yaml
Labels: bug

#217 Add aqua for tool management
  .github/renovate.json
  .github/workflows/ci.yaml
  aqua.yaml
Labels: chore

#227 Fix docker-compose call
  aqua.yaml
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
  pkg/virt/shims.go
Labels: bug

#223 .gitignore generator
  cmd/init.go
  cmd/init_test.go
  cmd/up.go
  cmd/up_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/generators/generator.go
  pkg/generators/generator_test.go
  pkg/generators/git_generator.go
  pkg/generators/git_generator_test.go
Labels: feature

#230 Fix default local blueprint
  pkg/blueprint/blueprint_handler.go
  pkg/generators/git_generator_test.go
Labels: bug

#233 Use statically typed colima configuration
  go.mod
  go.sum
  pkg/virt/colima_virt.go
Labels: chore

#238 Fix docker host and aws var issue
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
  pkg/env/shims.go
Labels: bug

#251 Renovate updates
  .github/renovate.json
Labels: chore

#252 Removed aqua section
  .github/renovate.json
Labels: chore

#248 Add sops to aqua file
  aqua.yaml
Labels: dependencies, chore

#253 Removed extra tags
  .github/renovate.json
Labels: chore

#277 automerge
  .github/renovate.json
Labels: chore

#280 removed automerge flag
  .github/renovate.json
Labels: chore

#289 consistent labels
  .github/renovate.json
Labels: chore

#294 Improve config jsonnet stability
  .gitignore
  .tool-versions
  cmd/init_test.go
  cmd/root_test.go
  go.mod
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/blueprint_v1alpha1.go
  pkg/blueprint/blueprint_v1alpha1_test.go
  pkg/blueprint/shims.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/aws/aws_config.go
  pkg/config/aws/aws_config_test.go
  pkg/config/cluster/cluster_config.go
  pkg/config/cluster/cluster_config_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/defaults.go
  pkg/config/dns/dns_config.go
  pkg/config/dns/dns_config_test.go
  pkg/config/docker/docker_config.go
  pkg/config/docker/docker_config_test.go
  pkg/config/git/git_config.go
  pkg/config/git/git_config_test.go
  pkg/config/terraform/terraform_config.go
  pkg/config/terraform/terraform_config_test.go
  pkg/config/vm/vm_config.go
  pkg/config/vm/vm_config_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/constants/constants.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller_test.go
  pkg/env/aws_env_test.go
  pkg/env/terraform_env_test.go
  pkg/services/dns_service_test.go
  pkg/services/git_livereload_service_test.go
  pkg/services/localstack_service_test.go
  pkg/services/registry_service_test.go
  pkg/virt/colima_virt.go
  pkg/virt/colima_virt_test.go
  pkg/virt/docker_virt_test.go
  pkg/virt/shims.go
Labels: chore

#295 Default registry mirrors
  .gitignore
  aqua.yaml
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/config/docker/docker_config.go
  pkg/config/docker/docker_config_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/constants/constants.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/generators/git_generator.go
  pkg/generators/git_generator_test.go
  pkg/services/dns_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/virt/docker_virt_test.go
Labels: feature

#300 Windsor hook
  cmd/hook.go
  cmd/hook_test.go
  go.mod
  go.sum
  pkg/shell/hooks.go
  pkg/shell/mock_shell.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/shims.go
Labels: enhancement

#301 Don't inject COMPOSE_FILE
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
Labels: bug

#316 Update README.md
  README.md
Labels: chore

#323 Fix restarting nodes on second `windsor up`
  go.mod
  go.sum
  pkg/services/dns_service.go
  pkg/services/talos_controlplane_service.go
  pkg/services/talos_worker_service.go
  pkg/shell/shell.go
Labels: bug

#325 Apply --verbose flag to shell commands
  cmd/down.go
  cmd/down_test.go
  cmd/init.go
  cmd/init_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/up.go
  cmd/up_test.go
  docs/install/install.md
  go.sum
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/shell/mock_shell.go
  pkg/shell/mock_shell_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
Labels: enhancement

#327 Improved terraform messaging
  pkg/stack/windsor_stack.go
  pkg/stack/windsor_stack_test.go
Labels: enhancement

#330 Add gitops/flux to local.jsonnet
  pkg/blueprint/blueprint_v1alpha1.go
  pkg/blueprint/templates/local.jsonnet
  pkg/generators/terraform_generator.go
Labels: feature

#331 Fix blueprint terraform component merge logic
  pkg/blueprint/blueprint_v1alpha1.go
  pkg/blueprint/blueprint_v1alpha1_test.go
Labels: bug
