Repository windsorcli/cli, pull requests merged in 2025-02, with the labels that each got.

#531 REGISTRY_URL environment variable
  api/v1alpha1/docker/docker_config.go
  api/v1alpha1/docker/docker_config_test.go
  cmd/env.go
  cmd/env_test.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/constants/constants.go
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
  pkg/services/dns_service.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
  pkg/services/service_test.go
  pkg/services/talos_service.go
Labels: feature

#494 Add helm to the aqua.yaml file
  aqua.yaml
Labels: chore

#554 Pass controller through cli context
  cmd/check.go
  cmd/context.go
  cmd/down.go
  cmd/env.go
  cmd/env_test.go
  cmd/exec.go
  cmd/hook.go
  cmd/init.go
  cmd/init_test.go
  cmd/install.go
  cmd/root.go
  cmd/root_test.go
  cmd/up.go
Labels: chore

#560 Default blueprints reference core source
  pkg/blueprint/templates/local.jsonnet
Labels: bug

#567 Implement proper handling of local config of registry mirror
  pkg/blueprint/templates/local.jsonnet
Labels: bug

#570 Support web flow in workstation
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
Labels: feature

#571 Support for docker native virt driver
  .vscode/launch.json
  cmd/init.go
  cmd/init_test.go
  cmd/shims.go
  go.sum
  pkg/config/defaults.go
  pkg/config/mock_config_handler_test.go
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
  pkg/env/shims.go
Labels: feature

#574 Support for local volume storage driver
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/cluster/cluster_config_test.go
  cmd/down.go
  cmd/down_test.go
  cmd/shims.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/config/yaml_config_handler_test.go
  pkg/env/kube_env.go
  pkg/env/kube_env_test.go
  pkg/env/shims.go
  pkg/services/talos_service.go
  pkg/services/talos_service_test.go
Labels: feature

#578 Fix missing registry url
  .vscode/launch.json
  cmd/install.go
  cmd/install_test.go
  pkg/env/kube_env_test.go
Labels: bug

#581 Fix non-local windsor.yaml defaults
  cmd/init.go
  go.sum
  pkg/config/defaults.go
Labels: bug

#583 Don't ignore eth0 on docker
  pkg/blueprint/templates/local.jsonnet
Labels: bug

#575 0.4.0 Documentation
  docs/guides/environment-injection.md
  docs/guides/local-workstation.md
  docs/quick-start.md
  docs/reference/blueprint.md
  docs/reference/configuration.md
  docs/tutorial/hello-world.md
Labels: documentation, chore

#609 Complete terraform backends
  api/v1alpha1/terraform/terraform_config.go
  api/v1alpha1/terraform/terraform_config_test.go
  go.mod
  go.sum
  pkg/config/defaults.go
  pkg/env/shims.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
Labels: enhancement

#596 Windsor exec Fix
  .github/workflows/ci.yaml
  cmd/exec.go
  cmd/exec_test.go
  cmd/windsor/main.go
Labels: bug

#587 dockerfile-fix
  docs/tutorial/hello-world.md
Labels: chore

#619 Post 4.0.0 doc updates
  docs/guides/contexts.md
  docs/guides/environment-injection.md
  docs/guides/kustomize.md
  docs/guides/local-workstation.md
  docs/guides/terraform.md
  docs/index.md
  docs/install.md
  docs/quick-start.md
  docs/reference/blueprint.md
  docs/reference/configuration.md
  docs/reference/contexts.md
  docs/security/trusted-folders.md
  docs/tutorial/hello-world.md
Labels: documentation, chore

#620 Go 1.23.4
  .github/renovate.json
  aqua.yaml
  go.mod
  go.sum
Labels: dependencies

#631 Implement custom env printer
  pkg/config/config_handler.go
  pkg/config/mock_config_handler.go
  pkg/config/mock_config_handler_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/env/custom_env.go
  pkg/env/custom_env_test.go
Labels: feature

#632 Add SecretsProvider
  .vscode/launch.json
  api/v1alpha1/secrets/secrets_config.go
  api/v1alpha1/secrets/secrets_config_test.go
  aqua.yaml
  cmd/env.go
  cmd/env_test.go
  cmd/exec.go
  cmd/exec_test.go
  cmd/install.go
  cmd/install_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/up.go
  cmd/up_test.go
  pkg/config/config_handler.go
  pkg/config/config_handler_test.go
  pkg/config/mock_config_handler.go
  pkg/config/mock_config_handler_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/env/env.go
  pkg/secrets/mock_secrets_provider.go
  pkg/secrets/mock_secrets_provider_test.go
  pkg/secrets/secrets_provider.go
  pkg/secrets/secrets_provider_test.go
  pkg/shell/hooks.go
Labels: feature

#636 Don't throw error when determining compose command
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
Labels: bug

#664 Expanded secrets path parser
  pkg/secrets/op_cli_secrets_provider.go
  pkg/secrets/op_cli_secrets_provider_test.go
  pkg/secrets/secrets_provider.go
  pkg/secrets/secrets_provider_test.go
Labels: bug

#666 "Cache" secrets to improve windsor env performance
  .gitignore
  cmd/up.go
  cmd/up_test.go
  go.sum
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/env/custom_env.go
  pkg/env/custom_env_test.go
  pkg/env/shims.go
  pkg/secrets/op_cli_secrets_provider.go
  pkg/secrets/op_cli_secrets_provider_test.go
Labels: enhancement

#668 0.5.0 Documentation
  README.md
  docs/docker-compose.yaml
  docs/guides/contexts.md
  docs/guides/environment-injection.md
  docs/guides/kustomize.md
  docs/guides/local-workstation.md
  docs/guides/secrets.md
  docs/guides/terraform.md
  docs/index.md
  docs/reference/blueprint.md
  docs/reference/configuration.md
  docs/reference/contexts.md
  docs/security/secrets.md
  docs/security/trusted-folders.md
  docs/tutorial/hello-world.md
Labels: documentation, chore

#669 Fix localstack pro configuration
  pkg/services/localstack_service.go
  pkg/services/localstack_service_test.go
Labels: bug

#670 Auto-configure AWS config for localstack
  api/v1alpha1/aws/aws_config.go
  api/v1alpha1/aws/aws_config_test.go
  api/v1alpha1/config_types_test.go
  aqua.yaml
  go.mod
  pkg/config/yaml_config_handler_test.go
  pkg/constants/constants.go
  pkg/controller/mock_controller.go
  pkg/controller/real_controller.go
  pkg/di/mock_injector.go
  pkg/env/aws_env.go
  pkg/env/aws_env_test.go
  pkg/generators/aws_generator.go
  pkg/generators/aws_generator_test.go
  pkg/generators/shims.go
  pkg/services/localstack_service.go
Labels: feature

#671 Generate AWS terraform provider override when localstack is enabled
  .gitignore
  pkg/di/mock_injector_test.go
  pkg/env/shims.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
  pkg/generators/git_generator.go
  pkg/generators/git_generator_test.go
  pkg/services/localstack_service.go
  pkg/services/localstack_service_test.go
Labels: enhancement

#675 Windsor docker image
  .github/renovate.json
  .github/workflows/ci.yaml
  Dockerfile
  aqua.docker.yaml
  aqua.yaml
  docker-compose.yml
Labels: feature

#678 Sign binaries
  .goreleaser.yaml
  docs/install.md
Labels: chore
