Repository windsorcli/cli, pull requests merged in 2025-01, with the labels that each got.

#340 Windsor install
  cmd/env_test.go
  cmd/install.go
  cmd/install_test.go
  cmd/root_test.go
  cmd/up.go
  cmd/up_test.go
  go.mod
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/blueprint_v1alpha1.go
  pkg/blueprint/blueprint_v1alpha1_test.go
  pkg/blueprint/mock_blueprint_handler.go
  pkg/blueprint/mock_blueprint_handler_test.go
  pkg/blueprint/shims.go
  pkg/constants/constants.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
Labels: feature

#344 Reorg blueprint types => api/ folder
  api/v1alpha1/blueprint_types.go
  api/v1alpha1/blueprint_types_test.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/defaults.go
  pkg/blueprint/mock_blueprint_handler.go
  pkg/blueprint/mock_blueprint_handler_test.go
  pkg/generators/generator_test.go
  pkg/generators/terraform_generator.go
  pkg/generators/terraform_generator_test.go
  pkg/stack/stack_test.go
Labels: chore

#359 Docker Desktop vm driver
  .vscode/launch.json
  api/v1alpha1/blueprint_types_test.go
  cmd/install.go
  cmd/install_test.go
  cmd/up.go
  cmd/up_test.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/constants/constants.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
  pkg/env/shims.go
  pkg/generators/terraform_generator_test.go
  pkg/network/colima_network.go
  pkg/network/colima_network_test.go
  pkg/network/darwin_network.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network.go
  pkg/network/linux_network_test.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/shims.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/services/registry_service.go
  pkg/services/service.go
  pkg/services/service_test.go
  pkg/services/talos_controlplane_service.go
  pkg/services/talos_controlplane_service_test.go
  pkg/services/talos_worker_service.go
  pkg/services/talos_worker_service_test.go
  pkg/virt/docker_virt.go
Labels: feature

#363 Reflect local gitops
  .vscode/launch.json
  api/v1alpha1/blueprint_types.go
  api/v1alpha1/blueprint_types_test.go
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/yaml_config_handler.go
  pkg/constants/constants.go
  pkg/network/darwin_network.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
Labels: feature

#366 Default to docker desktop
  docs/tutorial/macos-quick-start.md
  go.mod
  go.sum
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/constants/constants.go
  pkg/network/darwin_network.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network.go
  pkg/network/linux_network_test.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
Labels: enhancement

#372 Static Colima config
  go.mod
  go.sum
  pkg/virt/colima_virt.go
Labels: bug, chore

#374 Corrected registry mirrors
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/controller/real_controller.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/mock_service.go
  pkg/services/mock_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
  pkg/services/service_test.go
Labels: bug

#377 Project generator
  api/v1alpha1/blueprint_types.go
  go.mod
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/config/docker/docker_config.go
  pkg/config/docker/docker_config_test.go
  pkg/controller/mock_controller.go
  pkg/controller/real_controller.go
  pkg/generators/kustomize_generator.go
  pkg/generators/kustomize_generator_test.go
  pkg/generators/shims.go
  pkg/generators/terraform_generator.go
  pkg/generators/terraform_generator_test.go
  pkg/services/registry_service.go
Labels: feature

#401 Project level windsor.yaml config
  .gitignore
  .tf_modules/cluster/talos/.terraform.lock.hcl
  .tf_modules/cluster/talos/main.tf
  .tf_modules/cluster/talos/variables.tf
  .tf_modules/gitops/flux/.terraform.lock.hcl
  .tf_modules/gitops/flux/main.tf
  .tf_modules/gitops/flux/variables.tf
  .vscode/launch.json
  cmd/exec_test.go
  cmd/init.go
  cmd/init_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/shims.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/config/config.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/generators/generator_test.go
  pkg/generators/git_generator.go
  pkg/generators/git_generator_test.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/shims.go
  pkg/stack/stack_test.go
  pkg/stack/windsor_stack_test.go
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
Labels: enhancement

#402 Added BaseToolsManager class
  .tf_modules/cluster/talos/.terraform.lock.hcl
  .tf_modules/cluster/talos/main.tf
  .tf_modules/cluster/talos/variables.tf
  .tf_modules/gitops/flux/.terraform.lock.hcl
  .tf_modules/gitops/flux/main.tf
  .tf_modules/gitops/flux/variables.tf
  cmd/init.go
  cmd/root.go
  cmd/up.go
  cmd/up_test.go
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network_test.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/windows_network_test.go
  pkg/tools/mock_tools_manager.go
  pkg/tools/mock_tools_manager_test.go
  pkg/tools/shims.go
  pkg/tools/tools_manager.go
  pkg/tools/tools_manager_test.go
Labels: chore

#421 Version windsor config
  .gitignore
  api/v1alpha1/aws/aws_config.go
  api/v1alpha1/aws/aws_config_test.go
  api/v1alpha1/blueprint_types.go
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/cluster/cluster_config_test.go
  api/v1alpha1/config_types.go
  api/v1alpha1/config_types_test.go
  api/v1alpha1/dns/dns_config.go
  api/v1alpha1/dns/dns_config_test.go
  api/v1alpha1/docker/docker_config.go
  api/v1alpha1/docker/docker_config_test.go
  api/v1alpha1/git/git_config.go
  api/v1alpha1/git/git_config_test.go
  api/v1alpha1/terraform/terraform_config.go
  api/v1alpha1/terraform/terraform_config_test.go
  api/v1alpha1/utils.go
  api/v1alpha1/vm/vm_config.go
  api/v1alpha1/vm/vm_config_test.go
  cmd/root_test.go
  pkg/config/config_handler.go
  pkg/config/defaults.go
  pkg/config/mock_config_handler.go
  pkg/config/mock_config_handler_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/controller/mock_controller_test.go
  pkg/env/aws_env_test.go
  pkg/env/terraform_env_test.go
  pkg/services/dns_service_test.go
  pkg/services/git_livereload_service_test.go
  pkg/services/localstack_service_test.go
  pkg/services/registry_service_test.go
  pkg/virt/docker_virt_test.go
Labels: chore

#408 Add trusted folder support
  .github/workflows/ci.yaml
  cmd/env.go
  cmd/env_test.go
  cmd/init.go
  cmd/init_test.go
  go.mod
  go.sum
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/shell/mock_shell.go
  pkg/shell/mock_shell_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/shims.go
Labels: enhancement, security

#451 Update git-livereload image reference
  pkg/constants/constants.go
Labels: chore

#448 Updated core reference
  pkg/blueprint/templates/local.jsonnet
Labels: chore

#396 0.3.0 Documentation
  README.md
  api/v1alpha1/aws/aws_config.go
  docs/assets/css/extra.css
  docs/guides/contexts.md
  docs/guides/environment-injection.md
  docs/guides/kustomize.md
  docs/guides/local-workstation.md
  docs/guides/terraform.md
  docs/index.md
  docs/install.md
  docs/nav.yaml
  docs/quick-start.md
  docs/reference/blueprint.md
  docs/reference/configuration.md
  docs/reference/contexts.md
  docs/security/trusted-folders.md
  docs/tutorial/hello-world.md
Labels: documentation, chore

#467 Fix windsor up on windows
  pkg/blueprint/templates/local.jsonnet
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/shell/hooks.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/windows_shell.go
  pkg/shell/windows_test.go
Labels: bug

#461 Installation changes
  docs/install.md
Labels: chore

#469 Fix version issue
  docs/install.md
Labels: bug

#470 Fix windows installation instructions
  docs/install.md
Labels: documentation, chore

#471 Updated docs to add windsor install
  docs/quick-start.md
  docs/tutorial/hello-world.md
Labels: bug, documentation

#489 Include patches and components when generating kustomization
  pkg/blueprint/blueprint_handler.go
Labels: bug

#490 Worker nodeports
  .vscode/launch.json
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/cluster/cluster_config_test.go
  docs/reference/configuration.md
  pkg/config/config_handler.go
  pkg/config/defaults.go
  pkg/config/mock_config_handler.go
  pkg/config/mock_config_handler_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/services/talos_worker_service.go
  pkg/services/talos_worker_service_test.go
Labels: feature

#497 Blueprint configmap substitutions
  api/v1alpha1/blueprint_types.go
  api/v1alpha1/blueprint_types_test.go
  api/v1alpha1/dns/dns_config.go
  api/v1alpha1/dns/dns_config_test.go
  docs/guides/local-workstation.md
  docs/reference/configuration.md
  go.mod
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/config/defaults.go
  pkg/network/darwin_network.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network.go
  pkg/network/linux_network_test.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/git_livereload_service.go
  pkg/services/localstack_service.go
  pkg/services/localstack_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
  pkg/services/service_test.go
  pkg/services/talos_controlplane_service.go
  pkg/services/talos_controlplane_service_test.go
  pkg/services/talos_worker_service.go
  pkg/services/talos_worker_service_test.go
Labels: enhancement

#499 Optional DNS records
  api/v1alpha1/dns/dns_config.go
  api/v1alpha1/dns/dns_config_test.go
  docs/reference/configuration.md
  go.sum
  pkg/blueprint/blueprint_handler.go
  pkg/constants/constants.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
Labels: feature

#500 Include CONTEXT value in configmap
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
Labels: enhancement

#505 Flux webhook
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/constants/constants.go
Labels: feature

#508 Combine controlplane and worker service
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/cluster/cluster_config_test.go
  docs/reference/configuration.md
  pkg/config/defaults.go
  pkg/config/yaml_config_handler_test.go
  pkg/controller/real_controller.go
  pkg/services/talos_controlplane_service.go
  pkg/services/talos_controlplane_service_test.go
  pkg/services/talos_service.go
  pkg/services/talos_service_test.go
Labels: chore

#509 Enforce ordering of kustomize components
  api/v1alpha1/blueprint_types.go
Labels: bug

#511 Network configuration
  api/v1alpha1/config_types.go
  api/v1alpha1/config_types_test.go
  api/v1alpha1/docker/docker_config.go
  api/v1alpha1/docker/docker_config_test.go
  api/v1alpha1/network/network_config.go
  api/v1alpha1/network/network_config_test.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/blueprint_handler_test.go
  pkg/config/defaults.go
  pkg/services/dns_service_test.go
  pkg/services/registry_service_test.go
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
  pkg/virt/shims_test.go
Labels: feature
