Repository windsorcli/cli, pull requests merged in 2025-04, with the labels that each got.

#916 Non-Local Workflow Fixes
  cmd/down.go
  cmd/env.go
  cmd/init.go
  cmd/init_test.go
  cmd/install.go
  cmd/up.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
Labels: bug

#917 Expand default blueprint templating options
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/config_types.go
  api/v1alpha1/config_types_test.go
  cmd/init.go
  cmd/init_test.go
  pkg/blueprint/blueprint_handler.go
  pkg/blueprint/templates/default.jsonnet
  pkg/blueprint/templates/local.jsonnet
  pkg/config/defaults.go
  pkg/network/darwin_network.go
Labels: enhancement

#930 Attempt fix for ghost renovate packages
  go.mod
  go.sum
Labels: chore

#938 Use cluster.platform in the blueprint jsonnet
  pkg/blueprint/templates/default.jsonnet
Labels: bug

#941 Fix idempotency when configuring network on darwin
  pkg/network/darwin_network.go
Labels: bug

#937 Add IDs to goreleaser
  .goreleaser.yaml
Labels: chore

#951 Selectively load env vars internally
  cmd/down.go
  cmd/down_test.go
  cmd/init.go
  cmd/init_test.go
  cmd/install.go
  cmd/install_test.go
  cmd/up.go
  cmd/up_test.go
  pkg/controller/controller.go
Labels: bug

#952 Include WINDSOR_SESSION_TOKEN
  cmd/context.go
  cmd/context_test.go
  pkg/env/shims.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
Labels: enhancement

#955 Merge CustomEnv in to WindsorEnv
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/real_controller.go
  pkg/env/custom_env.go
  pkg/env/custom_env_test.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
Labels: chore

#961 Add `WINDSOR_MANAGED_*` variable
  cmd/env.go
  cmd/env_test.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/mock_env.go
  pkg/env/mock_env_test.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
Labels: enhancement

#964 Strategic clearing of environment variables
  .vscode/launch.json
  cmd/context.go
  cmd/context_test.go
  cmd/env.go
  cmd/env_test.go
  pkg/config/config_handler.go
  pkg/config/config_handler_test.go
  pkg/config/shims.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller_test.go
  pkg/env/aws_env_test.go
  pkg/env/docker_env_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/kube_env_test.go
  pkg/env/mock_env.go
  pkg/env/mock_env_test.go
  pkg/env/omni_env_test.go
  pkg/env/talos_env_test.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
  pkg/shell/mock_shell.go
  pkg/shell/mock_shell_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/shims.go
  pkg/shell/unix_shell.go
  pkg/shell/unix_test.go
  pkg/shell/windows_shell.go
  pkg/shell/windows_test.go
Labels: enhancement

#966 Default to use DOCKER_HOST if defined
  pkg/env/docker_env.go
Labels: bug

#970 Always print DOCKER_HOST
  cmd/init.go
  cmd/init_test.go
  go.mod
  go.sum
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
Labels: bug

#981 Use CoreDNS in docker network and for node endpoints
  pkg/network/darwin_network.go
  pkg/network/darwin_network_test.go
  pkg/network/linux_network.go
  pkg/network/linux_network_test.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/windows_network.go
  pkg/network/windows_network_test.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
  pkg/services/service_test.go
  pkg/services/talos_service.go
  pkg/services/talos_service_test.go
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
Labels: enhancement

#991 Use domains instead of IPs for cluster node IPs
  cmd/env.go
  pkg/blueprint/templates/default.jsonnet
  pkg/constants/constants.go
  pkg/services/dns_service.go
  pkg/services/dns_service_test.go
  pkg/services/git_livereload_service.go
  pkg/services/git_livereload_service_test.go
  pkg/services/localstack_service.go
  pkg/services/localstack_service_test.go
  pkg/services/mock_service.go
  pkg/services/mock_service_test.go
  pkg/services/registry_service.go
  pkg/services/registry_service_test.go
  pkg/services/service.go
  pkg/services/service_test.go
  pkg/services/talos_service.go
  pkg/services/talos_service_test.go
  pkg/virt/docker_virt.go
  pkg/virt/docker_virt_test.go
Labels: enhancement

#992 Warn when not in a trusted directory
  cmd/root.go
  cmd/root_test.go
Labels: enhancement

#996 Add secrets.md to nav
  docs/guides/secrets-management.md
  docs/nav.yaml
Labels: bug

#997 1Password SDK Secrets Provider
  .github/renovate.json
  .goreleaser.yaml
  .vscode/launch.json
  aqua.yaml
  cmd/env.go
  cmd/env_test.go
  cmd/install_test.go
  go.mod
  go.sum
  pkg/config/config_handler_test.go
  pkg/config/mock_config_handler_test.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/real_controller.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
  pkg/secrets/mock_secrets_provider.go
  pkg/secrets/mock_secrets_provider_test.go
  pkg/secrets/op_cli_secrets_provider.go
  pkg/secrets/op_cli_secrets_provider_test.go
  pkg/secrets/op_sdk_secrets_provider.go
  pkg/secrets/op_sdk_secrets_provider_test.go
  pkg/secrets/secrets_provider.go
  pkg/secrets/secrets_provider_test.go
  pkg/secrets/shims.go
  pkg/secrets/sops_secrets_provider.go
Labels: enhancement

#1000 Allow cluster image specification
  api/v1alpha1/cluster/cluster_config.go
  api/v1alpha1/cluster/cluster_config_test.go
  pkg/constants/constants.go
  pkg/services/talos_service.go
  pkg/services/talos_service_test.go
Labels: enhancement

#1001 Add LoadConfigString
  pkg/config/config_handler.go
  pkg/config/mock_config_handler.go
  pkg/config/mock_config_handler_test.go
  pkg/config/yaml_config_handler.go
  pkg/config/yaml_config_handler_test.go
Labels: chore

#1055 Add style guide and assets
  .cursorrules
  .vscode/go.code-snippets
  STYLE.md
  test.txt
Labels: chore

#1072 Env and shell packages follows STYLD.md guidelines
  pkg/constants/constants.go
  pkg/env/aws_env.go
  pkg/env/aws_env_test.go
  pkg/env/docker_env.go
  pkg/env/docker_env_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/kube_env.go
  pkg/env/kube_env_test.go
  pkg/env/mock_env.go
  pkg/env/mock_env_test.go
  pkg/env/omni_env.go
  pkg/env/omni_env_test.go
  pkg/env/shims.go
  pkg/env/shims_test.go
  pkg/env/talos_env.go
  pkg/env/talos_env_test.go
  pkg/env/terraform_env.go
  pkg/env/terraform_env_test.go
  pkg/env/windsor_env.go
  pkg/env/windsor_env_test.go
  pkg/shell/mock_shell.go
  pkg/shell/mock_shell_test.go
  pkg/shell/secure_shell.go
  pkg/shell/secure_shell_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/shims.go
  pkg/shell/shims_test.go
  pkg/shell/unix_shell.go
  pkg/shell/unix_shell_test.go
  pkg/shell/unix_test.go
  pkg/shell/windows_shell.go
  pkg/shell/windows_shell_test.go
  pkg/shell/windows_test.go
Labels: chore

#1076 Refactor controller to use constructor factory functions
  cmd/check_test.go
  cmd/down_test.go
  cmd/hook_test.go
  cmd/install_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/up_test.go
  cmd/version.go
  cmd/version_test.go
  cmd/windsor/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mock_controller.go
  pkg/controller/mock_controller_test.go
  pkg/controller/real_controller.go
  pkg/controller/real_controller_test.go
  pkg/network/mock_network.go
  pkg/network/shims.go
Labels: chore

#1064 Add pre-release support
  .github/workflows/build-artifacts.yaml
  .github/workflows/ci.yaml
  .goreleaser.yaml
Labels: enhancement

#1077 Prerelease 2, adding build-artifacts action
  .github/workflows/build-artifacts.yaml
  .github/workflows/dispatch-build-artifacts.yaml
Labels: chore
